# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17d8ff5eb5af8a17cfee0a7f4e54a86c36c4cc83949c06381f871a60f4cd95b0c3c7578b422b0eee1829740bcc962bfa9ef5c11e187a32c037ad426cff2915d

test:
  secret_key_base: cde014c20cf493795cde8ff84941afa50c745cc4e263d056f87281841301ed0dac1519cb7f34994ade57ab0ff9730014fc9f867e76ca01a1ea92034e04ca4d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
